name: casino_test
description: Casino test application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.3.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
